// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagementSystem;

public partial class kitchen
{
    public string user_name { get; set; }

    public string pass_word { get; set; }
}