// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Configuration;

namespace HotelManagementSystem;

public partial class FrontEndReservationContext : DbContext
{
    public FrontEndReservationContext()
    {
    }

    public FrontEndReservationContext(DbContextOptions<FrontEndReservationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<reservation> reservations { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["FrontEndConnStr"].ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<reservation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC070939E04D");

            entity.ToTable("reservation");

            entity.Property(e => e.apt_suite)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.arrival_time).HasColumnType("date");
            entity.Property(e => e.birth_day)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.card_cvc)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.card_exp)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.card_number)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.card_type)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.city).IsRequired();
            entity.Property(e => e.email_address).IsRequired();
            entity.Property(e => e.first_name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.gender)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.last_name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.leaving_time).HasColumnType("date");
            entity.Property(e => e.payment_type)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.phone_number)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.room_floor)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.room_number)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.room_type)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.state)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.street_address).IsRequired();
            entity.Property(e => e.zip_code)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}