// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Configuration;

namespace HotelManagementSystem;

public partial class LoginMgrContext : DbContext
{
    public LoginMgrContext()
    {
    }

    public LoginMgrContext(DbContextOptions<LoginMgrContext> options)
        : base(options)
    {
    }

    public virtual DbSet<frontend> frontends { get; set; }

    public virtual DbSet<kitchen> kitchens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConfigurationManager.ConnectionStrings["LoginMgrConnStr"].ConnectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<frontend>(entity =>
        {
            entity.HasKey(e => e.user_name).HasName("PK_Table");

            entity.ToTable("frontend");

            entity.Property(e => e.user_name).HasMaxLength(50);
            entity.Property(e => e.pass_word)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<kitchen>(entity =>
        {
            entity.HasKey(e => e.user_name).HasName("PK__kitchen__7628B51D2FDAF8B5");

            entity.ToTable("kitchen");

            entity.Property(e => e.user_name).HasMaxLength(50);
            entity.Property(e => e.pass_word)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}